export interface BusinessModel {
  title: string;
  category: string;
  tags: string;
  challengeAddressed: string;
  businessStage: string;
  resourceType: string;
  timeInvestment: string;
  difficultyLevel: string;
  prerequisites: string;
  expectedOutcome: string;
  keywords: string;
  description: string;
}

export const businessModels: BusinessModel[] = [
  {
    title: "Sacred 1:1 Spiritual Coaching",
    category: "Coaching Models",
    tags: "coaching, transformation, healing",
    challengeAddressed: "Monetizing spiritual gifts",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Beginner",
    prerequisites: "Coaching training",
    expectedOutcome: "$3-10k monthly",
    keywords: "spiritual coaching 1on1",
    description: "Deep transformation work with individuals"
  },
  {
    title: "Group Soul Circle Coaching",
    category: "Coaching Models",
    tags: "group coaching, circles, community",
    challengeAddressed: "Scaling impact",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Group facilitation skills",
    expectedOutcome: "$5-15k monthly",
    keywords: "group coaching circles community",
    description: "Monthly group transformation circles"
  },
  {
    title: "Spiritual Business Mastermind",
    category: "Coaching Models",
    tags: "mastermind, business, spiritual",
    challengeAddressed: "Combining spirituality + business",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Business experience",
    expectedOutcome: "$10-50k monthly",
    keywords: "mastermind business spiritual",
    description: "High-level spiritual entrepreneur community"
  },
  {
    title: "Sacred Ceremony Facilitation",
    category: "Ceremony Models",
    tags: "ceremonies, rituals, healing",
    challengeAddressed: "Creating meaningful experiences",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Intermediate",
    prerequisites: "Ceremony training",
    expectedOutcome: "$500-5k per event",
    keywords: "ceremony ritual facilitation",
    description: "Weddings, life transitions, healing ceremonies"
  },
  {
    title: "Digital Course: Spiritual Awakening",
    category: "Course Models",
    tags: "courses, awakening, digital",
    challengeAddressed: "Passive income creation",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Intermediate",
    prerequisites: "Teaching ability",
    expectedOutcome: "$5-20k monthly",
    keywords: "digital course spiritual awakening",
    description: "Self-paced transformation journey"
  },
  {
    title: "Membership: Daily Spiritual Practice",
    category: "Membership Models",
    tags: "membership, daily practice, community",
    challengeAddressed: "Recurring revenue",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "2 months",
    difficultyLevel: "Intermediate",
    prerequisites: "Content creation",
    expectedOutcome: "$2-10k monthly",
    keywords: "membership daily spiritual practice",
    description: "Monthly spiritual practice community"
  },
  {
    title: "Retreat Planning & Hosting",
    category: "Event Models",
    tags: "retreats, immersion, transformation",
    challengeAddressed: "High-value offerings",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Event planning",
    expectedOutcome: "$10-100k per retreat",
    keywords: "retreat planning hosting",
    description: "Multi-day transformational experiences"
  },
  {
    title: "Spiritual Business Consulting",
    category: "Consulting Models",
    tags: "consulting, business, strategy",
    challengeAddressed: "Expertise monetization",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Advanced",
    prerequisites: "Business expertise",
    expectedOutcome: "$5-25k monthly",
    keywords: "spiritual business consulting",
    description: "Helping others build spiritual businesses"
  },
  {
    title: "Sacred Art & Creative Services",
    category: "Creative Models",
    tags: "art, creativity, healing",
    challengeAddressed: "Creative expression income",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Beginner",
    prerequisites: "Artistic ability",
    expectedOutcome: "$1-5k monthly",
    keywords: "sacred art creative services",
    description: "Healing art, mandalas, spiritual design"
  },
  {
    title: "Spiritual Writing & Publishing",
    category: "Content Models",
    tags: "writing, books, publishing",
    challengeAddressed: "Thought leadership",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Writing skills",
    expectedOutcome: "$2-20k monthly",
    keywords: "spiritual writing publishing",
    description: "Books, blogs, spiritual content"
  },
  {
    title: "Intuitive Reading Services",
    category: "Reading Models",
    tags: "intuitive, psychic, guidance",
    challengeAddressed: "Psychic gift monetization",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Intermediate",
    prerequisites: "Intuitive abilities",
    expectedOutcome: "$2-8k monthly",
    keywords: "intuitive psychic reading",
    description: "Personal guidance sessions"
  },
  {
    title: "Energy Healing Practice",
    category: "Healing Models",
    tags: "energy healing, reiki, chakras",
    challengeAddressed: "Healing gift monetization",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Intermediate",
    prerequisites: "Healing certification",
    expectedOutcome: "$3-12k monthly",
    keywords: "energy healing reiki practice",
    description: "Remote and in-person healing"
  },
  {
    title: "Spiritual Life Coaching",
    category: "Coaching Models",
    tags: "life coaching, spiritual, guidance",
    challengeAddressed: "Life transformation",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Coaching certification",
    expectedOutcome: "$4-15k monthly",
    keywords: "spiritual life coaching",
    description: "Holistic life guidance"
  },
  {
    title: "Sacred Business Templates",
    category: "Digital Products",
    tags: "templates, business, sacred",
    challengeAddressed: "Passive product income",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Beginner",
    prerequisites: "Design skills",
    expectedOutcome: "$1-5k monthly",
    keywords: "business templates sacred",
    description: "Ready-made spiritual business tools"
  },
  {
    title: "Meditation Teacher Training",
    category: "Education Models",
    tags: "meditation, teaching, certification",
    challengeAddressed: "Teaching spiritual practices",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Meditation expertise",
    expectedOutcome: "$5-25k per cohort",
    keywords: "meditation teacher training",
    description: "Certifying new meditation teachers"
  },
  {
    title: "Spiritual Podcast Monetization",
    category: "Content Models",
    tags: "podcast, monetization, spiritual",
    challengeAddressed: "Content monetization",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Intermediate",
    prerequisites: "Podcasting skills",
    expectedOutcome: "$2-15k monthly",
    keywords: "podcast spiritual monetization",
    description: "Spiritual podcast with multiple revenue streams"
  },
  {
    title: "Oracle Card Creation",
    category: "Product Models",
    tags: "oracle cards, divination, creation",
    challengeAddressed: "Creative product income",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Artistic ability",
    expectedOutcome: "$5-50k per deck",
    keywords: "oracle cards creation divination",
    description: "Custom oracle card deck development"
  },
  {
    title: "Spiritual App Development",
    category: "Tech Models",
    tags: "app, technology, spiritual",
    challengeAddressed: "Tech integration",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "12 months",
    difficultyLevel: "Advanced",
    prerequisites: "Tech team",
    expectedOutcome: "$10-100k monthly",
    keywords: "spiritual app technology",
    description: "Meditation, guidance, or practice apps"
  },
  {
    title: "Sacred Space Rental",
    category: "Physical Models",
    tags: "space rental, ceremonies, events",
    challengeAddressed: "Location-based income",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Physical space",
    expectedOutcome: "$2-10k monthly",
    keywords: "sacred space rental ceremonies",
    description: "Renting space for spiritual events"
  },
  {
    title: "Spiritual Affiliate Marketing",
    category: "Marketing Models",
    tags: "affiliate, partnerships, spiritual",
    challengeAddressed: "Partnership income",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Beginner",
    prerequisites: "Audience",
    expectedOutcome: "$500-5k monthly",
    keywords: "affiliate marketing spiritual",
    description: "Promoting aligned spiritual products"
  },
  {
    title: "Donation-Based Offerings",
    category: "Alternative Models",
    tags: "donations, gifts, abundance",
    challengeAddressed: "Non-traditional pricing",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Beginner",
    prerequisites: "None",
    expectedOutcome: "Heart-based income",
    keywords: "donation based offerings gifts",
    description: "Gift economy spiritual services"
  },
  {
    title: "Spiritual Business Accelerator",
    category: "Intensive Models",
    tags: "accelerator, intensive, business",
    challengeAddressed: "High-touch transformation",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Proven results",
    expectedOutcome: "$25-100k per cohort",
    keywords: "business accelerator spiritual",
    description: "6-month intensive business program"
  },
  {
    title: "Moon Cycle Business Planning",
    category: "Planning Models",
    tags: "moon cycles, planning, ritual",
    challengeAddressed: "Spiritual business timing",
    businessStage: "All stages",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Astrology knowledge",
    expectedOutcome: "Aligned business rhythm",
    keywords: "moon cycle business planning",
    description: "Business planning with lunar cycles"
  },
  {
    title: "Sacred Sales Conversations",
    category: "Sales Models",
    tags: "sales, sacred, conversations",
    challengeAddressed: "Sales without sleaze",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Intermediate",
    prerequisites: "Sales training",
    expectedOutcome: "Higher conversion",
    keywords: "sacred sales conversations",
    description: "Heart-centered sales approach"
  },
  {
    title: "Spiritual Subscription Box",
    category: "Product Models",
    tags: "subscription, box, spiritual",
    challengeAddressed: "Physical product income",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Product sourcing",
    expectedOutcome: "$5-25k monthly",
    keywords: "subscription box spiritual",
    description: "Monthly spiritual product curation"
  },
  {
    title: "Energy Clearing for Businesses",
    category: "Service Models",
    tags: "energy clearing, business, healing",
    challengeAddressed: "Business energy healing",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Advanced",
    prerequisites: "Energy work training",
    expectedOutcome: "$1-5k per clearing",
    keywords: "energy clearing business healing",
    description: "Clearing stagnant business energy"
  },
  {
    title: "Spiritual Content Creation",
    category: "Content Models",
    tags: "content, creation, spiritual",
    challengeAddressed: "Consistent content income",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "2 months",
    difficultyLevel: "Intermediate",
    prerequisites: "Content skills",
    expectedOutcome: "$2-10k monthly",
    keywords: "spiritual content creation",
    description: "Blogs, videos, social media content"
  },
  {
    title: "Sacred Partnership Programs",
    category: "Partnership Models",
    tags: "partnerships, collaboration, sacred",
    challengeAddressed: "Collaboration income",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Network",
    expectedOutcome: "$3-15k monthly",
    keywords: "sacred partnership collaboration",
    description: "Joint ventures with spiritual alignment"
  },
  {
    title: "Intuitive Business Strategy",
    category: "Strategy Models",
    tags: "intuitive, strategy, guidance",
    challengeAddressed: "Strategic clarity",
    businessStage: "All stages",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Advanced",
    prerequisites: "Business experience",
    expectedOutcome: "Clear direction",
    keywords: "intuitive business strategy",
    description: "Using intuition for business decisions"
  },
  {
    title: "Spiritual Licensing Programs",
    category: "Licensing Models",
    tags: "licensing, certification, spiritual",
    challengeAddressed: "Scalable teaching",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Proven methodology",
    expectedOutcome: "$10-50k monthly",
    keywords: "licensing certification spiritual",
    description: "License your spiritual methodology"
  },
  {
    title: "Heart-Centered Copywriting",
    category: "Service Models",
    tags: "copywriting, heart-centered, authentic",
    challengeAddressed: "Authentic marketing",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Writing skills",
    expectedOutcome: "$3-12k monthly",
    keywords: "copywriting heart-centered authentic",
    description: "Spiritual copy that converts"
  },
  {
    title: "Sacred Brand Photography",
    category: "Service Models",
    tags: "photography, branding, sacred",
    challengeAddressed: "Visual brand alignment",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Intermediate",
    prerequisites: "Photography skills",
    expectedOutcome: "$2-8k monthly",
    keywords: "brand photography sacred",
    description: "Soul-aligned visual branding"
  },
  {
    title: "Spiritual Business Audit",
    category: "Service Models",
    tags: "audit, assessment, spiritual",
    challengeAddressed: "Business alignment check",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Advanced",
    prerequisites: "Business analysis",
    expectedOutcome: "$1-5k per audit",
    keywords: "business audit spiritual",
    description: "Comprehensive spiritual business review"
  },
  {
    title: "Moon Circle Membership",
    category: "Membership Models",
    tags: "moon circles, rituals, community",
    challengeAddressed: "Monthly recurring revenue",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "2 months",
    difficultyLevel: "Intermediate",
    prerequisites: "Moon knowledge",
    expectedOutcome: "$2-8k monthly",
    keywords: "moon circle membership community",
    description: "Monthly new moon ceremony community"
  },
  {
    title: "Spiritual Speaking Engagements",
    category: "Speaking Models",
    tags: "speaking, events, spiritual",
    challengeAddressed: "Visibility and income",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Speaking skills",
    expectedOutcome: "$2-15k per event",
    keywords: "spiritual speaking engagements",
    description: "Paid spiritual speaking opportunities"
  },
  {
    title: "Sacred Workspace Design",
    category: "Service Models",
    tags: "workspace, design, energy",
    challengeAddressed: "Environment optimization",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Intermediate",
    prerequisites: "Design skills",
    expectedOutcome: "$3-10k per project",
    keywords: "workspace design sacred energy",
    description: "Creating soul-aligned workspaces"
  },
  {
    title: "Spiritual Business Coaching Certification",
    category: "Certification Models",
    tags: "certification, coaching, business",
    challengeAddressed: "Teaching others",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "12 months",
    difficultyLevel: "Advanced",
    prerequisites: "Proven results",
    expectedOutcome: "$15-75k per cohort",
    keywords: "coaching certification spiritual business",
    description: "Certifying spiritual business coaches"
  },
  {
    title: "Goddess Circle Facilitation",
    category: "Facilitation Models",
    tags: "goddess, feminine, circles",
    challengeAddressed: "Divine feminine work",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Feminine wisdom",
    expectedOutcome: "$1-5k per circle",
    keywords: "goddess circle feminine facilitation",
    description: "Women's empowerment circles"
  },
  {
    title: "Sacred Plant Medicine Integration",
    category: "Integration Models",
    tags: "plant medicine, integration, healing",
    challengeAddressed: "Post-ceremony support",
    businessStage: "Advanced",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Plant medicine experience",
    expectedOutcome: "$5-20k monthly",
    keywords: "plant medicine integration healing",
    description: "Supporting spiritual journeys"
  },
  {
    title: "Spiritual Business Incubator",
    category: "Incubator Models",
    tags: "incubator, startup, spiritual",
    challengeAddressed: "Supporting new entrepreneurs",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "12 months",
    difficultyLevel: "Advanced",
    prerequisites: "Business success",
    expectedOutcome: "$20-100k per cohort",
    keywords: "business incubator spiritual",
    description: "6-month spiritual business launch program"
  },
  {
    title: "Crystal Healing Business",
    category: "Healing Models",
    tags: "crystals, healing, energy",
    challengeAddressed: "Crystal work monetization",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Beginner",
    prerequisites: "Crystal knowledge",
    expectedOutcome: "$1-6k monthly",
    keywords: "crystal healing business",
    description: "Crystal healing sessions and products"
  },
  {
    title: "Spiritual Travel Experiences",
    category: "Experience Models",
    tags: "travel, spiritual, journeys",
    challengeAddressed: "Experiential income",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Travel planning",
    expectedOutcome: "$5-50k per trip",
    keywords: "spiritual travel experiences",
    description: "Sacred site pilgrimages and retreats"
  },
  {
    title: "Akashic Records Reading",
    category: "Reading Models",
    tags: "akashic records, soul, guidance",
    challengeAddressed: "Soul-level guidance",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Advanced",
    prerequisites: "Akashic training",
    expectedOutcome: "$2-10k monthly",
    keywords: "akashic records reading soul",
    description: "Deep soul guidance sessions"
  },
  {
    title: "Spiritual Business Mastercourse",
    category: "Course Models",
    tags: "mastercourse, business, comprehensive",
    challengeAddressed: "Complete education",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Teaching ability",
    expectedOutcome: "$10-50k monthly",
    keywords: "mastercourse spiritual business",
    description: "Comprehensive spiritual business education"
  },
  {
    title: "Sacred Sexuality Coaching",
    category: "Coaching Models",
    tags: "sexuality, sacred, healing",
    challengeAddressed: "Sexual healing work",
    businessStage: "Advanced",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Sexuality training",
    expectedOutcome: "$5-25k monthly",
    keywords: "sacred sexuality coaching healing",
    description: "Healing relationship with sexuality"
  },
  {
    title: "Spiritual Emergency Support",
    category: "Support Models",
    tags: "crisis, emergency, spiritual",
    challengeAddressed: "Crisis support income",
    businessStage: "Advanced",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Advanced",
    prerequisites: "Crisis training",
    expectedOutcome: "$3-15k monthly",
    keywords: "spiritual emergency crisis support",
    description: "Supporting spiritual emergencies"
  },
  {
    title: "Divine Feminine Business",
    category: "Feminine Models",
    tags: "divine feminine, business, flow",
    challengeAddressed: "Feminine approach to business",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 months",
    difficultyLevel: "Intermediate",
    prerequisites: "Feminine wisdom",
    expectedOutcome: "Flowing business growth",
    keywords: "divine feminine business flow",
    description: "Business aligned with feminine principles"
  },
  {
    title: "Shamanic Healing Practice",
    category: "Healing Models",
    tags: "shamanic, healing, soul retrieval",
    challengeAddressed: "Ancient healing monetization",
    businessStage: "Advanced",
    resourceType: "Framework",
    timeInvestment: "2 years",
    difficultyLevel: "Advanced",
    prerequisites: "Shamanic training",
    expectedOutcome: "$5-30k monthly",
    keywords: "shamanic healing practice",
    description: "Traditional shamanic healing services"
  },
  {
    title: "Spiritual Tech Consulting",
    category: "Consulting Models",
    tags: "technology, spiritual, integration",
    challengeAddressed: "Tech-spiritual bridge",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Tech expertise",
    expectedOutcome: "$10-40k monthly",
    keywords: "spiritual tech consulting",
    description: "Helping spiritual businesses with technology"
  },
  {
    title: "Sacred Sound Healing",
    category: "Healing Models",
    tags: "sound healing, bowls, vibration",
    challengeAddressed: "Sound healing income",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Sound training",
    expectedOutcome: "$2-8k monthly",
    keywords: "sound healing bowls sacred",
    description: "Sound baths and healing sessions"
  },
  {
    title: "Spiritual Business Podcast",
    category: "Media Models",
    tags: "podcast, business, education",
    challengeAddressed: "Authority building",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Intermediate",
    prerequisites: "Podcasting skills",
    expectedOutcome: "$3-15k monthly",
    keywords: "podcast spiritual business",
    description: "Educational spiritual business content"
  },
  {
    title: "Angel Reading Services",
    category: "Reading Models",
    tags: "angel, guidance, messages",
    challengeAddressed: "Angelic guidance income",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Intermediate",
    prerequisites: "Angel connection",
    expectedOutcome: "$2-10k monthly",
    keywords: "angel reading guidance messages",
    description: "Connecting clients with angelic guidance"
  },
  {
    title: "Spiritual Copywriting Agency",
    category: "Agency Models",
    tags: "copywriting, agency, spiritual",
    challengeAddressed: "Scaling writing services",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Team building",
    expectedOutcome: "$10-50k monthly",
    keywords: "copywriting agency spiritual",
    description: "Full-service spiritual marketing copy"
  },
  {
    title: "Sacred Breathwork Facilitation",
    category: "Facilitation Models",
    tags: "breathwork, healing, transformation",
    challengeAddressed: "Breath healing income",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 months",
    difficultyLevel: "Advanced",
    prerequisites: "Breathwork training",
    expectedOutcome: "$3-12k monthly",
    keywords: "breathwork facilitation sacred",
    description: "Transformational breathing sessions"
  },
  {
    title: "Spiritual Business Software",
    category: "Software Models",
    tags: "software, tools, spiritual",
    challengeAddressed: "Software development",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "12 months",
    difficultyLevel: "Advanced",
    prerequisites: "Development team",
    expectedOutcome: "$20-200k monthly",
    keywords: "spiritual business software",
    description: "Apps and tools for spiritual entrepreneurs"
  },
  {
    title: "Manifestation Coaching Practice",
    category: "Coaching Models",
    tags: "manifestation, creation, abundance",
    challengeAddressed: "Teaching manifestation",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 month",
    difficultyLevel: "Intermediate",
    prerequisites: "Manifestation mastery",
    expectedOutcome: "$3-15k monthly",
    keywords: "manifestation coaching practice",
    description: "Helping others manifest their dreams"
  },
  {
    title: "Sacred Geometry Design Services",
    category: "Design Models",
    tags: "sacred geometry, design, art",
    challengeAddressed: "Spiritual design income",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "2 weeks",
    difficultyLevel: "Intermediate",
    prerequisites: "Design skills",
    expectedOutcome: "$2-8k monthly",
    keywords: "sacred geometry design services",
    description: "Spiritual art and design services"
  },
  {
    title: "Spiritual Business Retreat Center",
    category: "Physical Models",
    tags: "retreat center, hosting, space",
    challengeAddressed: "Location-based business",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "2 years",
    difficultyLevel: "Advanced",
    prerequisites: "Significant capital",
    expectedOutcome: "$25-150k monthly",
    keywords: "retreat center spiritual business",
    description: "Operating a spiritual retreat facility"
  },
  {
    title: "Astrology Business Consulting",
    category: "Consulting Models",
    tags: "astrology, business, timing",
    challengeAddressed: "Astrological business guidance",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "3 months",
    difficultyLevel: "Advanced",
    prerequisites: "Astrology expertise",
    expectedOutcome: "$5-25k monthly",
    keywords: "astrology business consulting",
    description: "Using astrology for business decisions"
  },
  {
    title: "Spiritual Affiliate Network",
    category: "Network Models",
    tags: "affiliate, network, spiritual",
    challengeAddressed: "Community monetization",
    businessStage: "Scaling",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Large network",
    expectedOutcome: "$5-30k monthly",
    keywords: "affiliate network spiritual",
    description: "Network of spiritual product affiliates"
  },
  {
    title: "Sacred Text Translation Services",
    category: "Service Models",
    tags: "translation, sacred texts, spiritual",
    challengeAddressed: "Language services",
    businessStage: "Starting out",
    resourceType: "Framework",
    timeInvestment: "1 week",
    difficultyLevel: "Intermediate",
    prerequisites: "Language skills",
    expectedOutcome: "$2-10k monthly",
    keywords: "translation sacred texts spiritual",
    description: "Translating spiritual content"
  },
  {
    title: "Spiritual Business Legal Services",
    category: "Legal Models",
    tags: "legal, spiritual business, protection",
    challengeAddressed: "Legal specialization",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "2 years",
    difficultyLevel: "Advanced",
    prerequisites: "Legal degree",
    expectedOutcome: "$15-75k monthly",
    keywords: "legal spiritual business services",
    description: "Legal services for spiritual entrepreneurs"
  },
  {
    title: "Sacred Architecture Consulting",
    category: "Consulting Models",
    tags: "architecture, sacred space, design",
    challengeAddressed: "Space design income",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Architecture background",
    expectedOutcome: "$10-50k per project",
    keywords: "architecture sacred space consulting",
    description: "Designing sacred spaces and buildings"
  },
  {
    title: "Spiritual Investment Consulting",
    category: "Financial Models",
    tags: "investment, spiritual, ethical",
    challengeAddressed: "Ethical investing",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Financial background",
    expectedOutcome: "$5-25k monthly",
    keywords: "spiritual investment consulting",
    description: "Helping with ethical investment choices"
  },
  {
    title: "Energy-Based Marketing Agency",
    category: "Agency Models",
    tags: "marketing, energy, spiritual",
    challengeAddressed: "Spiritual marketing services",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "6 months",
    difficultyLevel: "Advanced",
    prerequisites: "Marketing expertise",
    expectedOutcome: "$15-75k monthly",
    keywords: "energy marketing agency spiritual",
    description: "Full-service spiritual marketing"
  },
  {
    title: "Conscious Business Broker",
    category: "Brokerage Models",
    tags: "business broker, conscious, spiritual",
    challengeAddressed: "Business transactions",
    businessStage: "Established",
    resourceType: "Framework",
    timeInvestment: "12 months",
    difficultyLevel: "Advanced",
    prerequisites: "Business valuation",
    expectedOutcome: "$10-100k per deal",
    keywords: "conscious business broker",
    description: "Facilitating spiritual business sales"
  }
];